### PR TITLE
Version 0.2.0

### PR DESCRIPTION
**Pull request by dns2utf8**

### CODE REVIEW

**Comment by DirkHeinke** [comment]
I guess without the installation of LaTeX this will not work ;-)

**Comment by dns2utf8** [comment]
Agreed, the build starts up but can not compile any tex files.

I will work on this during the weekend.

**Comment by DirkHeinke** [comment]
I updated the container to 0.2.0. But thanks for the PR.

**Comment by dns2utf8** [comment]
Was fun, thanks for the Update.

**Pull request closed without merging**
